/*-------Stagging database------------*/

CREATE DATABASE vbs_stagging;

drop table user_roles;
drop table user_files;
drop table users;
drop table user_attempts;

CREATE TABLE USER_ATTEMPTS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ATTEMPTS INT(2),
  LAST_MODIFIED timestamp,
  CONSTRAINT IDX_ATTEMPTS_ID PRIMARY KEY (ID));

CREATE  TABLE USERS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(20) NOT NULL ,
  PASSWORD VARCHAR(60) NOT NULL ,
  SALT VARCHAR(60),
  COMPANY VARCHAR(50),
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  ADDRESS VARCHAR(150) NOT NULL, 
  COUNTRY VARCHAR(45) NOT NULL,
  PROVINCE VARCHAR(40) NOT NULL,
  ZIP INT(7),
  PHONE VARCHAR(15) NOT NULL,
  EMAIL VARCHAR(45) NOT NULL,
  PREFERRED VARCHAR(45),
  STAGE VARCHAR(45),
  SOFTWARE VARCHAR(100) NOT NULL,
  FREQUENCY VARCHAR(45),
  ABOUT VARCHAR(351) NOT NULL,
  ENABLED BIT(1) NOT NULL DEFAULT FALSE,
  VERIFICATION_HASH VARCHAR(60),
  ACCOUNT_NON_EXPIRED BIT(1) NOT NULL DEFAULT TRUE,/*accountNonExpired*/
  CREDENTIALS_NON_EXPIRED BIT(1) NOT NULL DEFAULT TRUE,/*credentialsNonExpired*/
  ACCOUNT_NON_LOCKED BIT(1) NOT NULL DEFAULT TRUE,/*accountNonLocked*/
  CREATED timestamp,
  ATTEMPTS_ID INT(11),
  CONSTRAINT IDX_USER_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ATTEMPTS_ID FOREIGN KEY (ATTEMPTS_ID) REFERENCES USER_ATTEMPTS (ID) ON DELETE CASCADE);
  
CREATE TABLE USER_ROLES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) NOT NULL,
  AUTHORITY VARCHAR(45) NOT NULL,
  CREATED timestamp,
  CONSTRAINT IDX_ROLES_ID PRIMARY KEY (ID),
  CONSTRAINT FK_USER_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE);
  
CREATE TABLE USER_FILES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) NOT NULL,
  FILE_NAME VARCHAR(100) NOT NULL,
  FILE_TYPE VARCHAR(20) NOT NULL,
  FILE_SIZE BIGINT(11) NOT NULL,
  CREATED timestamp,
  CONSTRAINT IDX_FILES_ID PRIMARY KEY (ID),
  CONSTRAINT FK_FILES_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE);


INSERT into USER_ATTEMPTS (ATTEMPTS, LAST_MODIFIED) values (0, now());

INSERT INTO USERS(
USERNAME,PASSWORD,SALT,COMPANY,FIRST_NAME,LAST_NAME,ADDRESS,COUNTRY,PROVINCE,ZIP,PHONE,EMAIL,PREFERRED,STAGE,SOFTWARE,FREQUENCY,ABOUT,ENABLED,CREATED, ATTEMPTS_ID)
VALUES('sherazahmed', '$2a$10$c.hYRC6AHOlBfXymxyv7pe/OljnzLDzYVGMeUNnbd.700.encKlmS', '[B@402dae86', 'VISION BUSINESS SOLUTIONS', 'Sheraz', 'Ahmed', '400 Thompson Creek Rd', 'United States', 'Maryland', '21666', 
'2028304056', 'sheraz.ahmed@visionbizsolutions.com', 'Email or Phone', 'Decided to outsource', 'Quickbooks', 'Weekly', 
'I am writing to get to know about how can I get my bookkeeping done is reasonable cost on weekly basis', TRUE, NOW(), 1);

INSERT INTO USER_ROLES(USER_ID, AUTHORITY, CREATED)
VALUES (1, 'ROLE_USER', NOW());

INSERT INTO USER_ROLES(USER_ID, AUTHORITY, CREATED)
VALUES (1, 'ROLE_ADMIN', NOW());
